### ISSUE TITLE
Get your invite

### ISSUE THREAD

**Issue by JuIioCesar** [unamfi/Get-your-invite#1]
Make a comment on this issue to get an invite to join. You will get a reaction when your request is accepted.

**Comment by pabloem** [comment]
Yo! ; )

**Comment by vicenteguerra** [comment]
Yo :D

**Comment by alexchaps** [comment]
Yo :)

**Comment by rzavalet** [comment]
Yop!

**Comment by JuIioCesar** [comment]
¡Gracias a todos por participar! Estoy cerrando este issue debido a que ahora los invites son automatizados via la página https://unamfi.herokuapp.com/ 😄
